version: '3.4'

services:
  looplex.dotnet.samples.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    expose:
      - "80"
    ports:
      - "8080:80"
      - "1443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  looplex.dotnet.samples.db:
    environment:
     - SA_PASSWORD=!ooplex_D0tNet!s@
     - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
