services:
  looplex.dotnet.samples.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=looplex
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    expose:
      - "80"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  looplex.dotnet.samples.routing.db:
    environment:
      - SA_PASSWORD=!ooplex_D0tNet!s@
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  looplex.dotnet.samples.academic.db:
    environment:
     - SA_PASSWORD=!ooplex_D0tNet!s@
     - ACCEPT_EULA=Y
    ports:
      - "1435:1433"
